// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc319.RecyleRush.subsystems;

import org.usfirst.frc319.RecyleRush.Robot;
import org.usfirst.frc319.RecyleRush.RobotMap;
import org.usfirst.frc319.RecyleRush.commands.*;

import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class RearClaw extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    DoubleSolenoid clawPnuematic = RobotMap.rearClawClawPnuematic;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public boolean bClawClosed;

	
    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
    
   /* public boolean getRearClawState(){
    	return rearClawState;
    }
    */
    
    public void close(){
    	clawPnuematic.set(DoubleSolenoid.Value.kReverse);
    	bClawClosed = true;
    	System.out.println("closed");
    }
    
    public void open(){
    	clawPnuematic.set(DoubleSolenoid.Value.kForward);
    	bClawClosed = false;
    	System.out.println("open");
    
    }
    public boolean isClawClosed(){
    	return bClawClosed;
    }

	
}

