// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc319.RecyleRush.subsystems;

import org.usfirst.frc319.RecyleRush.RobotMap;
import org.usfirst.frc319.RecyleRush.commands.*;
import edu.wpi.first.wpilibj.*;

import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class RearArm extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    DoubleSolenoid topPnuematic = RobotMap.rearArmTopPnuematic;
    DoubleSolenoid bottomPnuematic = RobotMap.rearArmBottomPnuematic;
    
    DoubleSolenoid chainPneumatic = RobotMap.rearArmChainPnuematic;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    public boolean topPneumaticExtended = false;
    public boolean bottomPneumaticExtended = false;
    
    public boolean isLowered = false;

    public void initDefaultCommand() {
        
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
    public void extend(){
    	System.out.println("Extending rear arm.");
    	topPnuematic.set(DoubleSolenoid.Value.kForward); //Extended
    	bottomPnuematic.set(DoubleSolenoid.Value.kReverse); //Extended
    	topPneumaticExtended = true;
    	bottomPneumaticExtended = true;
    }
    public void retract(){
    	topPnuematic.set(DoubleSolenoid.Value.kReverse); //Retracted
    	bottomPnuematic.set(DoubleSolenoid.Value.kForward);//Retracted
    	topPneumaticExtended = false;
    	bottomPneumaticExtended = false;
    }
    public void lower(){
    	topPnuematic.set(DoubleSolenoid.Value.kForward); //Extended
    	bottomPnuematic.set(DoubleSolenoid.Value.kForward);//Retracted
    	topPneumaticExtended = true;
    	bottomPneumaticExtended = false;
    }
    
    public boolean isExtended(){
    	return topPneumaticExtended && bottomPneumaticExtended;
    }
    
    public boolean isRetracted(){
    	return !topPneumaticExtended && !bottomPneumaticExtended;
    }
    
    public boolean isLowered(){
    	return isLowered;
    }
    
    public void chainLower(){
    	chainPneumatic.set(DoubleSolenoid.Value.kReverse);
    	isLowered = true;
    }
    public void chainRaise(){
    	chainPneumatic.set(DoubleSolenoid.Value.kForward);
    	isLowered = false;
    }
}

