// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc319.RecyleRush.commands;

import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc319.RecyleRush.Robot;

/**
 *
 */
public class  ActiveCollectorSnugTote extends Command {
	double threshold = 0;
	
    public ActiveCollectorSnugTote(double range) {
    	threshold = range;
        requires(Robot.elevator);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    	Robot.elevator.setToteInCollectorState(false);
    	
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	//Robot.elevator.printDetectorValues();
    	Robot.activeCollector.collect(.5); //Why is the speed of the collector set to the range threshold?
    	
    	
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
    	 
    	 return Robot.elevator.isToteWithinRange(threshold);
    }

    // Called once after isFinished returns true
    protected void end() {
    	Robot.elevator.setToteInCollectorState(true);
    	Robot.activeCollector.stop();
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    }
}
