// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc319.RecyleRush.commands;
import edu.wpi.first.wpilibj.command.CommandGroup;

/**
 *
 */
public class Auto3Tote2ContainerWithNewRearUnit extends CommandGroup {
    
    public  Auto3Tote2ContainerWithNewRearUnit() {
      
    	//REAR ARM SHOULD BE EXTENDED BUT JUST IN CASE
    	addSequential(new SetCollectorTotePresence(false));
    	addSequential(new DistancePIDResetEncoders());
    	
    	
    	//GRAB REAR CONTAINER
    	addSequential(new RearClawClose());
    	
    	//LIFTS REAR ARM AND GRABS REAR CONTAINER,LIFTS ELEVATOR SO TOTE CAN SLIDE UNDER
    	addParallel(new AutoRearShoulderGoToStorageHeight()); //Parallels are tied to
    	addSequential(new AutoCollectContainer());//  the next sequential^^^ is finished=Elevator is Up
    	
    	
    	//DRIVES FORWARD UNTIL 1st TOTE IS DETECTED 
    	
    	//addParallel(new SmartCollect());
    	addParallel(new SmartCollectAndAlignWithOpenCollector());
    	addSequential(new AutoDriveStraight(-0.7));   	
    	addSequential(new ActiveCollectorStop());
    	
    	addSequential(new StackAndGrab());//"opens claw,elevator to bottom,detect, close claw"
    	//^Eric's note: may cause issues with double detector scanning;		  // is finsihed  = claw is closed
    	
    													//these motors are "Cold Warm"
    	
    	addSequential(new ActiveCollectorOpen());
    	addSequential(new DistancePIDResetEncoders());    	
    	//Lifts ELEVATOR to Clearance AND TURNS 180
    	addParallel(new GrabAndLiftToClearance()); //Lifting and turning at the same time
    	
		addSequential(new AutoRotate(138)); // was 137  was (practice bot was 185 "reliably")
		
		//Changed from 150 to 200 for BOB 2 Testing
								//^^This is the value in which Bob2 turns 180 (was 208)
								//output capped at 0.8
		
		// DRIVES FORWARD UNTIL RF's SEES 2nd TOTE
		addSequential(new SetCollectorTotePresence(false));
		//addParallel(new SmartCollect());
		addParallel(new SmartCollectAndAlignWithOpenCollector());
		addSequential(new AutoDriveStraight(-0.7)); // is finished = istoteready   	
    	addSequential(new ActiveCollectorStop());
    	addSequential(new DistancePIDResetEncoders());
    	addSequential(new AutoDriveForwardUntilDistanceIsReached(3));
    		
    	// OPENS CLAW AND DRIVES FORWARD UNTIL ELEVATOR IS DESCENDED
		addSequential(new StackAndGrab());
		addSequential(new ActiveCollectorOpen());
    	
		//LIFTS 2nd TOTE while driving forward until elevator is ascended
		addSequential(new AutoDriveForwardAndLift());
		addSequential(new SetCollectorTotePresence(false));
    	  
		//addParallel(new SmartCollect());
		addParallel(new SmartCollectAndAlignWithOpenCollector());	
		addSequential(new AutoDriveStraight(-0.75));//was -0.63   	
    	addSequential(new ActiveCollectorStop());
		
		//3rd tote is collected
		//addSequential(new StackAndGrab());
		//addSequential(new AutoElevatorTwoInchPosition());
		
		
		//"Fairly Confident" till here
    	// ROTATES 90 
    	//addSequential(new AutoRotateLooseToleranceWhileKeepingTote(85));//was 99
    	//addSequential(new ActiveCollectorSnugTote(5.0));
		
    	//DRIVES BACKWARD INTO AUTO ZONE
    	addSequential(new DistancePIDResetEncoders());
    	//addParallel(new AutoFinalizeStack());
    	
    	addSequential(new AutoLastTurnSequence());
    	
    	addSequential(new ToteClawOpen());
    	addParallel(new AutoElevatorLiftContainerFromAutoStackHeight());
    	//addSequential(new AutoDriveStraightForwardToDistance(1, 24.0));//was 90
		addSequential(new DistancePIDResetEncoders());
		addSequential(new AutoDriveStraightForwardToDistance(.75, 16));//Slowing down at the end was .5,18   
		
					//DERRICK NEDCMP Q49 Suggestion reduce to 20"-22" to be sure we don't go to far.   Q60 was 24
		
		addSequential(new DistancePIDResetEncoders());
		//addSequential(new AutoDriveStraightForwardToDistance(.3, 6));
		//TURN RIGHT, TO BRING TOTES AND REAR CONTAINER INTO ZONE
		//addSequential(new AutoRotate(107.5));
		
		//addSequential(new AutoDriveStop(0.5));  
		
		//DROP ALL THE THINGS AND BACK AWAY
		//addParallel(new SequentialRelease());
		//addParallel(new ScoreTotes());
		
		//addSequential(new ActiveCollectorOpen());
		addSequential(new DistancePIDResetEncoders());
		addSequential(new AutoActiveCollectorReject());
		//addSequential(new AutoDriveStraightBackwardToDistance(0.75, -10.0));
		//addSequential(new ElevatorCap3());
		addSequential(new ActiveCollectorOpen());
    }
}
