// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc319.RecyleRush.commands;
import edu.wpi.first.wpilibj.command.CommandGroup;

/**
 *
 */
public class Auto3Tote2ContainerWithCollectorWheels extends CommandGroup {
    
    public  Auto3Tote2ContainerWithCollectorWheels() {
      
    	//REAR ARM SHOULD BE EXTENDED BUT JUST IN CASE
    	addSequential(new SetCollectorTotePresence(false));
    	addSequential(new DistancePIDResetEncoders());
    	addSequential(new RearArmExtend());
    	
    	//GRAB REAR CONTAINER
    	addSequential(new RearClawClose());
    	
    	//LIFTS REAR ARM AND GRABS REAR CONTAINER,LIFTS ELEVATOR SO TOTE CAN SLIDE UNDER
    	addParallel(new AutoRearShoulderGoToFourTote()); //Parallels are tied to
    	addSequential(new AutoCollectContainer());//  the next sequential^^^ is finished=Elevator is Up
    	
    	
    	//DRIVES FORWARD UNTIL 1st TOTE IS DETECTED 
    	addParallel(new SmartCollect());
    	addSequential(new AutoDriveStraight(-0.7));// is finished is in command as 12.5 // was -0.855
    	//is finished in command as 7.5
    	//addSequential(new AutoDriveStraightStage1()); // is finished = toteready you have to input the value 
    	//NOTE If drive straight finishes before smart collect wheels keep going?
    											//Pushes it Tp far
    	
    	
    	//PLACES CONTAINER ONTO TOTE/DROPS ELEVATOR DOWN AND GRABS 1st TOTE    	
    	
    	addSequential(new StackAndGrab());//"opens claw,elevator to bottom,detect, close claw"
    	//^Eric's note: may cause issues with double detector scanning;		  // is finsihed  = claw is closed
    	
    													//these motors are "Cold Warm"
    	
    	addSequential(new ActiveCollectorOpen());
    	addSequential(new DistancePIDResetEncoders());    	
    	//Lifts ELEVATOR to Clearance AND TURNS 180
    	addParallel(new GrabAndLiftToClearance()); //Lifting and turning at the same time
    	
		addSequential(new AutoRotate(140.5)); //Was 140 last time it worked... then it didn't 
		
		//Changed from 150 to 200 for BOB 2 Testing
								//^^This is the value in which Bob2 turns 180 (was 208)
								//output capped at 0.8
		
		// DRIVES FORWARD UNTIL RF's SEES 2nd TOTE
		addSequential(new SetCollectorTotePresence(false));
		addParallel(new SmartCollectAndAlignWithOpenCollector());
		addSequential(new AutoDriveStraight(-0.7)); // is finished = istoteready
    		
    	// OPENS CLAW AND DRIVES FORWARD UNTIL ELEVATOR IS DESCENDED
		addSequential(new StackAndGrab());
		addSequential(new ActiveCollectorOpen());
    	
		//LIFTS 2nd TOTE while driving forward until elevator is ascended
		addSequential(new AutoDriveForwardAndLift());
		addSequential(new SetCollectorTotePresence(false));
    	   		
		addParallel(new SmartCollectAndAlignWithOpenCollector());	
		addSequential(new AutoDriveStraight(-0.75));//was -0.63
		
		//3rd tote is collected
		addSequential(new StackAndGrab());
		addSequential(new AutoElevatorTwoInchPosition());
		
		
		//"Fairly Confident" till here
    	// ROTATES 90 
    	addSequential(new AutoRotateLooseTolerance(-65));//was 99
    	//addSequential(new ActiveCollectorSnugTote(5.0));
		
    	//DRIVES BACKWARD INTO AUTO ZONE
    	addSequential(new DistancePIDResetEncoders());
    	//addParallel(new AutoFinalizeStack());
		addSequential(new AutoDriveStraightBackwardToDistance(1.0,-76.5)); //was 90 
		
		//TURN RIGHT, TO BRING TOTES AND REAR CONTAINER INTO ZONE
		//addSequential(new AutoRotate(107.5));
		
		//addSequential(new AutoDriveStop(0.5));  
		
		//DROP ALL THE THINGS AND BACK AWAY
		//addParallel(new SequentialRelease());
		addParallel(new ScoreTotes());
		addSequential(new DistancePIDResetEncoders());
		addSequential(new AutoDriveStraightBackwardToDistance(0.75, -18.0));
		//addSequential(new ElevatorCap3());    	
    }
}
