// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc319.RecyleRush.commands;

import edu.wpi.first.wpilibj.Timer;
import edu.wpi.first.wpilibj.command.Command;

import org.usfirst.frc319.RecyleRush.Robot;

/**
 *
 */
public class  ElevatorHome extends Command {

    public ElevatorHome() {
    
        requires(Robot.elevator);
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    }
    //private int counter = 0;
    private int counter = Robot.elevator.encoderPosition();
    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    
    	counter = counter - 5 ;
    	//counter = counter + 5;
    	//Timer.delay(.2);
    //	if(!Robot.elevator.bottomLimitSwitch()){
    		Robot.elevator.driveElevatorDown(counter);
    //	}else{
    //		return;
    //	}
    	
     
    	
    
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return Robot.elevator.bottomLimitSwitch();
    }

    // Called once after isFinished returns true
    protected void end() {
    	Robot.elevator.resetEncoder();
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    }
}
