// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc319.RecyleRush.commands;
import org.usfirst.frc319.RecyleRush.Robot;

import edu.wpi.first.wpilibj.command.CommandGroup;

/**
 *
 */
public class InitializeAutoStack extends CommandGroup {
    
    public  InitializeAutoStack() {
        
    //	if(Robot.elevator.numberOfTotesPossessed == 0){ //used only for 1st Tote
    		
    		//addSequential(new PrepareToAquire()); // will open tote claw and lower to a collection position
    		//addSequential(new GrabAndLiftToClearance()); // will grab said tote and raise it to desired height
    		//addSequential(new IncrementToteCount());// ERIC's NOTE : Must test this... might need to be in Grab&LiftToClearance Command group
    		//SHOULD set Tote Counter to 1... ALSO Prints Tote Count
    		//addSequential(new PrintNumberOfTotes());//Print Tote counter # **REDUNDANT**
    		
    		
    	//}
    	//else if(Robot.elevator.numberOfTotesPossessed > 0 && Robot.elevator.numberOfTotesPossessed < 4){
    		//addSequential(new ActiveCollectorCollect());
    		
    		addSequential(new ElevatorDetectTote());  //Once command is enabled again, it'll search for a tote to be in position.
    		//addSequential(new ElevatorDisplay()); // TESTING: to make sure logic gets past this point
    		addSequential(new Stack()); // Normal stack sequence: *Release* Lower, grab, lift;
    		//addSequential(new IncrementToteCount()); // ERIC's NOTE : Must test this... might need to be in Grab&LiftToClearance Command group
    		//tote counter continues to rise^
    		//addSequential(new PrintNumberOfTotes()); //Print Tote counter # **REDUNDANT**
    	//}
    } // NOTE: This command only goes up to 4 totes... Due to container. Will need to work on Logic for 5 w/ no container.
    
}
