// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc319.RecyleRush.commands;
import edu.wpi.first.wpilibj.command.CommandGroup;

/**
 *
 */
public class PrepareToAquire extends CommandGroup {
    
    public  PrepareToAquire() {
       
    	addSequential(new ToteClawOpen()); // Tote Claw opens...
    	//addSequential(new ContainerClawOpen());
    	addSequential(new ElevatorFloorPickup()); //Lowers to "0" setpoint/ ie ground pickup
    	addSequential(new ElevatorDetectTote()); // waits for tote to be equally aligned with sensors for in position
    	addSequential(new ToteClawClose()); // closes tote claw...
    	
    	//addSequential(new PrintNumberOfTotes()); // Print statement for "I have # totes" **REDUNDANT**
    	
    
    }
}
