// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc319.RecyleRush.commands;
import org.usfirst.frc319.RecyleRush.Robot;

import edu.wpi.first.wpilibj.command.CommandGroup;

/**
 *
 */
public class SmartCollect extends CommandGroup {
    
    public  SmartCollect() {
    	
    	
    	addSequential(new ActiveCollectorClose());
        addSequential(new ActiveCollectorCollect());
        addSequential(new SmartCollectDetectTote(9.0));//was 7.5 before RF's moved to chassis
        //addSequential(new ActiveCollectorStop());
        addSequential(new ActiveCollectorAlignTote());//was 3.0 before RF's moved to chassis
        addSequential(new ActiveCollectorStop());
    } 
}
